# --- !Ups

create table "prices" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "price" DOUBLE not null,
  "time" DATE not null
);

create table "Currencies" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "base" VARCHAR(10) not null,
  "currency" VARCHAR(10) not null
);


# --- !Downs

drop table "prices" if exists;


# --- !Downs

drop table "Currencies" if exists;
